[package]
name = "ultrapubsub"
version = "0.1.0"
edition = "2021"

[lib]
name = "ultrapubsub"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26", features = ["extension-module"] }
pyo3-ffi = "0.26"
libc = "0.2.176"
memmap2 = "0.9.8"
nix = { version = "0.29", features = ["fs", "mman", "process", "event"] }
fcntl = "0.1"
